### ISSUE TITLE
create-eth-app used as dependency instead of CLI 

### ISSUE THREAD

**Issue by PaulRBerg** [Arbol-Project/Arbol-dApp#2]
Hi, thanks for trying [create-eth-app](https://github.com/paulrberg/create-eth-app), but you're not meant list it as a dependency. It's a command-line interface tool.

You can refer to the [Creating an App](https://github.com/paulrberg/create-eth-app/tree/89a9f219f210dde636e076fd2daa5882671e012b#creating-an-app) section for more details.

**Comment by dmp267** [comment]
Hi Paul,

Could you please point me to where [create-eth-app](https://github.com/paulrberg/create-eth-app) is listed as a dependency? Thank You.
